spring:
  datasource:
    url: ${Local_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${Local_REDIS_HOST}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${Local_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: dropify-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    com.dropify: DEBUG
    org.hibernate.SQL: DEBUG
