apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':common')
    implementation project(':event')
    implementation project(':web')
    implementation project(':user')
    implementation project(':notification')
    implementation 'org.springframework:spring-tx'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation project(':order')
    testImplementation project(':product')
    testImplementation project(':payment')
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.testcontainers:mysql'
    testRuntimeOnly 'com.mysql:mysql-connector-j'
}
